<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<LangVersion>Latest</LangVersion>
		<Nullable>enable</Nullable>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="9.0.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NMediator\NMediator.csproj" />
	</ItemGroup>

</Project>
