name: .NET Core

on:
  push:
    branches: [ feature/init ]
  pull_request:
    branches: [ feature/init ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    #- name: Build
      #run: dotnet build --configuration Release --no-restore
    #- name: Test
      #run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile="**/*.g.cs"
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build --configuration Release --no-restore
        testCommand: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile="**/*.g.cs".
        projectKey: jwoots_NMediator
        projectName: jwoots_NMediator
        sonarOrganisation: jwoots
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='**/*.opencover.xml"'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
