name: .NET Core

on:
  push:
    branches: [ feature/init ]
  pull_request:
    branches: [ feature/init ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v2
    #- name: Setup .NET Core
     # uses: actions/setup-dotnet@v1.9.0
     # with:
      #  dotnet-version: 6.0.x
    #- name: Install dependencies
     # run: dotnet restore
    #- name: Build
      #run: dotnet build --configuration Release --no-restore
    #- name: Test
      #run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile="**/*.g.cs"
    - name: SonarScanner for .NET 6 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        dotnetBuildArguments: --configuration Release
        dotnetTestArguments: /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile="**/*.g.cs".
        sonarProjectKey: jwoots_NMediator
        sonarProjectName: jwoots_NMediator
        sonarOrganization: jwoots
        sonarBeginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='**/*.opencover.xml"'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
